version: "1"
services:
  db1:
    build: ./db1
    environment:
      SA_PASSWORD: "toor0104~"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"
    container_name: db1
    hostname: db1